---
ingress-nginx:
  controller:
    kind: DaemonSet
    service:
      enabled: false
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    hostPort:
      enabled: true
      ports:
        http: 80
        https: 443
    resources:
      requests:
        cpu: 100m
        memory: 128Mi