apiVersion: v2
name: nginx-ingress-wrapper
description: Wrapper pro NGINX Ingress Helm chart
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: "4.10.0"
    repository: "https://kubernetes.github.io/ingress-nginx"