name: Create Release Merge Request

on:
  push:
    branches:
      - main
      - test

jobs:
  create-release-mr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Temporary Release Branch
        env:
          TMP_BRANCH: "${{ github.ref_name }}_release-temp"
        run: |
          # git checkout main
          # git pull origin main
          git checkout -B $TMP_BRANCH
          mkdir -p apps
          mv env/prod/* apps/
          rm -rf env
          git add .
          git commit -m "Automatická transformace: přesun ./env/prod do ./apps a smazání ./env"
          git push origin $TMP_BRANCH --force

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TMP_BRANCH: "${{ github.ref_name }}_release-temp"
        run: gh pr create --base release --head r$TMP_BRANCH --title "Automatická synchronizace release" --body "Tato větev obsahuje aktualizovaný release obsah podle main."
