# Full Argo diff before release
# argocd app diff ${{ github.ref_name }}
# argocd app diff argocd/example-app-nginx-example --local ./argo-apps/example-app/nginx-example


name: ArgoCD Diff Before Deployment

on:
  # pull_request:
  #   branches:
  #     - test

  push:
    branches:
      - test

jobs:
  argo-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

  fetch-apps:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.get-apps.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: STAGE - Get ArgoCD Applications
        id: get-apps
        run: |
          pushd env/stage
          APPS=$(for app in ./*/*/Chart.yml; do echo $app | awk -F'/' '{print $2"-"$3}'; done | xargs)
          echo "apps=[\"$(echo $APPS | sed 's/ /\",\"/g')\"]" >> $GITHUB_ENV
          echo "apps=[\"$(echo $APPS | sed 's/ /\",\"/g')\"]" >> $GITHUB_OUTPUT
          popd

  diff-apps:
    needs: fetch-apps
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJson(needs.fetch-apps.outputs.apps) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

      - name: Run ArgoCD Diff for ${{ matrix.app }}
        run: |
          echo ""
          echo "RUN: argocd app diff ${{ matrix.app }} --local ./argo-apps/${{ matrix.app }}"
          argocd --grpc-web --insecure app diff ${{ matrix.app }} --local ./env/stage/${{ matrix.app }}
        env:
          ARGOCD_SERVER: http://argocd.check-this.link
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}